sonar.sourceEncoding=UTF-8

# Código fuente y tests
sonar.sources=modulo_admin
sonar.tests=tests

# Reporte de cobertura en formato Cobertura XML de pytest
sonar.python.coverage.reportPaths=coverage.xml

# Exclusiones
sonar.exclusions=node_modules/**, .venv/**, tests/**